GET http://localhost:3000/produits

###
GET http://localhost:3000/produits/6883847228a238e075f923be

###
POST http://localhost:3000/produits
Content-Type: application/json

{
    "produitName": "pizza12",
    "price": 120,
    "stockStatus": "en stock"
}

###
PATCH http://localhost:3000/produits/688738b5f384016748f27f97
Content-Type: application/json

{
    "produitName": "tomate",
    "price": 12000,
    "stockStatus": "petit stock"
}


###
PATCH http://localhost:3000/produits/688738b5f384016748f27f97/en stock

###
DELETE http://localhost:3000/produits/688731c2f384016748f27f6d